### ISSUE TITLE
Module did not self-register error

### ISSUE THREAD

**Issue by slobad123** [dbousque/posix-semaphore#3]
I ran into a "Module did not self-register" when trying to `require("posix-semaphore")` in a worker thread (when it was also required by the main thread).

Some searching on the issue led me to these links
https://github.com/nodejs/node/issues/21783#issuecomment-429637117
https://nodejs.org/api/addons.html#addons_context_aware_addons

I am not familiar with C++ addons, but it looks like using NODE_MODULE_INIT in addon.cc rather than NODE_MODULE might apply here.

I would be happy to help test the change or can work on a PR when I get the time (though logging the issue for now). Thanks

**Comment by dbousque** [comment]
Hi @slobad123. Thanks for the report. It should be fixed in version 0.0.4, which has just been published. Let me know if that fixes it for you :)

**Comment by slobad123** [comment]
It works! You're the best. Thanks

**Comment by dbousque** [comment]
Haha thanks. Have a good one
